# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

increQIF_sub <- function(X, y, nobs, family, corstr, beta_old, maxit, tol) {
    .Call(`_RenewQIF_increQIF_sub`, X, y, nobs, family, corstr, beta_old, maxit, tol)
}

increQIF_test <- function(X, y, nobs, family, corstr, beta_old) {
    .Call(`_RenewQIF_increQIF_test`, X, y, nobs, family, corstr, beta_old)
}

increQIF <- function(X, y, nobs, family, corstr, beta_old, g_accum, G_accum, C_accum, maxit, tol) {
    .Call(`_RenewQIF_increQIF`, X, y, nobs, family, corstr, beta_old, g_accum, G_accum, C_accum, maxit, tol)
}


